CREATE TABLE IF NOT EXISTS CHAT_USER  (
  ID int AUTO_INCREMENT,
  NAME varchar(50) NOT NULL,
  PASSWORD varchar(65) NOT NULL,
  ROLE varchar(15) NOT NULL,
  LAST_PASSWORD_RESET_DATE datetime NOT NULL,
  PRIMARY KEY(ID)
);


CREATE TABLE IF NOT EXISTS ROOM  ( 
  ID int AUTO_INCREMENT,
  NAME varchar(50) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS USER_ROOM  ( 
  ROOM_ID int NOT NULL,
  USER_ID int NOT NULL,
  PRIMARY KEY(ROOM_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS MESSAGE  ( 
  ID int AUTO_INCREMENT,
  ROOM_ID int NULL,
  FROM_USER int NOT NULL,
  TO_USER int NOT NULL,
  MESSAGE varchar(256) NOT NULL,
  POSTED_ON datetime NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID),
  INDEX(ROOM_ID ,TO_USER)
);