INSERT INTO CHAT_USER(NAME, PASSWORD, ROLE, LAST_PASSWORD_RESET_DATE) 
VALUES("ADMIN", "PASSWORD", "ADMIN", now());

INSERT INTO CHAT_USER(NAME, PASSWORD, ROLE, LAST_PASSWORD_RESET_DATE) 
VALUES("USER1", "USER", "USER", now());

INSERT INTO CHAT_USER(NAME, PASSWORD, ROLE, LAST_PASSWORD_RESET_DATE) 
VALUES("USER2", "USER", "USER", now());


INSERT INTO ROOM(NAME ) 
VALUES("room1");

INSERT INTO ROOM(NAME ) 
VALUES("room2");

INSERT INTO ROOM(NAME ) 
VALUES("room3");

INSERT INTO USER_ROOM(ROOM_ID, USER_ID)
VALUE(1, 1);

INSERT INTO USER_ROOM(ROOM_ID, USER_ID)
VALUE(1, 2);


INSERT INTO MESSAGE(ROOM_ID, FROM_USER, TO_USER, MESSAGE)
VALUE(1, 1, 2, "this is a test message");

INSERT INTO MESSAGE(ROOM_ID, FROM_USER, TO_USER, MESSAGE)
VALUE(1, 1, 3, "this is a test message");

